CREATE DATABASE IRISDB;
USE IRISDB;

CREATE TABLE IRIS(
SEPALLENGTH FLOAT NOT NULL,
SEPALWIDTH FLOAT NOT NULL,
PETALLENGTH FLOAT NOT NULL,
PETALWIDTH FLOAT NOT NULL,
SPECIES VARCHAR(50) NOT NULL
);

SELECT * FROM IRIS;

-- VIEW 10 ROWS FROM IRIS DATASET
SELECT * FROM IRIS 
LIMIT 10;

SELECT DISTINCT SPECIES
FROM IRIS;

-- COUNT HOW MANY RECORD BELGONS TO EACH 
SELECT SPECIES , COUNT(*) AS COUNT
FROM IRIS 
GROUP BY SPECIES;

-- SHOW TOP 5 ROWS WITH LARGEST SEPALLENGTH
SELECT * FROM IRIS
ORDER BY SEPALLENGTH DESC
LIMIT 5;

-- 


USE PYTHONDB;
SHOW TABLES;
DESC EMPLOYEES;
SELECT * FROM EMPLOYEES;