CREATE DATABASE STUDENTDB;
USE STUDENTDB;

CREATE TABLE STUDENTS(
STUDENTID CHAR(4),
NAME VARCHAR(50),
MARKS INT
);
TRUNCATE STUDENTS;
INSERT INTO STUDENTS VALUES
('S001' , 'RAM' , 90),
('S002' , 'RAVI' , 80),
('S003' , 'KARAN' , 70),
('S004' , 'MEENA' , 60),
('S005' , 'RIYA' , 50),
('S006' , 'PRIYA', 40);
SELECT * FROM STUDENTS;

-- SIMPLE CASE STATEMENT
SELECT 
STUDENTID,NAME,MARKS,
CASE MARKS
WHEN 90 THEN "OUTSTANDING"
WHEN 80 THEN "EXCELLENT"
WHEN 70 THEN "VERY GOOD"
WHEN 60 THEN "GOOD"
WHEN 50 THEN "PASS"
ELSE "FAIL"
END AS REMARK
FROM STUDENTS;

-- SEARCHED CASE STATEMENT
CREATE DATABASE STUDENTDB2;
USE STUDENTDB2;

CREATE TABLE STUDENTS(
STUDENTID CHAR(4),
NAME VARCHAR(50),
MARKS INT
);
TRUNCATE STUDENTS;
INSERT INTO STUDENTS VALUES
('S001' , 'RAM' , 92),
('S002' , 'RAVI' , 84),
('S003' , 'KARAN' , 78),
('S004' , 'MEENA' , 67),
('S005' , 'RIYA' , 55),
('S006' , 'PRIYA', 40);
SELECT * FROM STUDENTS;

SELECT STUDENTID , NAME , MARKS,
CASE 
WHEN MARKS BETWEEN 90 AND 100 THEN "OUTSTANDING"
WHEN MARKS BETWEEN 80 AND 89 THEN "EXCELLENT"
WHEN MARKS BETWEEN 70 AND 79 THEN "VERY GOOD"
WHEN MARKS BETWEEN 60 AND 69 THEN "GOOD"
WHEN MARKS BETWEEN 50 AND 59 THEN "PASS"
ELSE "FAIL"
END AS REMARK
FROM STUDENTS;

-- ORDER OF EXECUTION
USE COMPANYDB;
CREATE TABLE EMPLOYEEINFO(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPARTMENT VARCHAR(30),
AGE INT,
SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEEINFO VALUES
(1, 'JOHN' , 'HR' , 28 , 40000),
(2, 'MARY' , 'HR' , 32 , 42000),
(3 , 'STEVE' , 'IT' , 26 , 50000),
(4 , 'AMAN' , 'IT' , 31 , 52000),
(5, 'BOB' , 'FINANCE' , 29, 41000),
(6 , 'EESHA' , 'FINANCE' , 29,41000),
(7 , 'TOM' , 'IT' , 27 , 49000),
(8, 'SARA', 'HR', 30, 43000),
(9, 'RAJ', 'FINANCE', 33, 45000),
(10, 'NAINA', 'IT', 35, 55000);

SELECT * FROM EMPLOYEEINFO;

-- I WANT TO KNOW WHICH DEPARTMENTS HAVE THAN 2 EMPLYEES,
-- BUT ONLY CONSIDER EMPLLYEES OLDER THAN 25
-- AND JUST SHOW ME THE FIRST 2 DEPARTMENTS IN ALPHABETICAL ORDER
-- ALSO IF BY CHANCE ANY DEPARTMENTS NAEMES REPATES , SHOW IT ONLY ONCE

SELECT DISTINCT DEPARTMENT , COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEEINFO
WHERE AGE > 25
GROUP BY DEPARTMENT
HAVING COUNT(*) > 2
ORDER BY DEPARTMENT
LIMIT 2;

-- FIND THE DEPARTMENT WHERE AVG SALARY OF EMPLLYEES WHO ARE OLDER THAN 27
-- IS MORE THAN 42000
-- SHOW ONLY DISTINCT DEPARTMENTS NAMES AND THEIR AVG SALARIES
-- ARRANGE IN ALPHABATICAL ORDER
-- SHOW ONLY TOP 2 DEPARTMENT

SELECT DISTINCT DEPARTMENT , AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEEINFO
WHERE AGE > 27
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 42000
ORDER BY DEPARTMENT
LIMIT 2;

