CREATE DATABASE JOINDEMO;
USE JOINDEMO;

-- INNER JOIN
CREATE TABLE EMP(
EMPID INT PRIMARY KEY,
FANAME VARCHAR(30),
AGE INT
);

CREATE TABLE SALARY(
SAL_ID INT PRIMARY KEY,
EMPID INT,
AMOUNT DECIMAL(10,2)
);

INSERT INTO EMP VALUES
(1,'A',24),(2,'B',25),(3,'C',26);

INSERT INTO SALARY VALUES
(101,1,50000),(102,2,55000);

SELECT E.EMPID, E.FANAME, S.AMOUNT
FROM EMP E
INNER JOIN SALARY S
ON E.EMPID = S.EMPID;

CREATE TABLE EMP2(
EMPID INT PRIMARY KEY,
FNAME VARCHAR(30),
AGE INT
);

CREATE TABLE SALARY2(
SAL_ID INT PRIMARY KEY,
EMPID INT,
AMOUNT DECIMAL(10,2)
);

INSERT INTO EMP2 VALUES
(1,'A',24),(2,'B',25),(3,'C',26);

INSERT INTO SALARY2 VALUES
(101,1,50000),(102,2,55000);

-- LEFT JOIN
SELECT E.EMPID,E.FNAME,S.AMOUNT
FROM EMP2 E 
LEFT JOIN SALARY2 S
ON E.EMPID = S.EMPID;

-- RIGHT JOIN
CREATE TABLE EMP3(
EMPID INT PRIMARY KEY,
FNAME VARCHAR(30),
AGE INT
);

CREATE TABLE SALARY3(
SAL_ID INT PRIMARY KEY,
EMPID INT,
AMOUNT DECIMAL(10,2)
);

INSERT INTO EMP3 VALUES
(1,'A',24),(2,'B',25),(3,'C',26);

INSERT INTO SALARY3 VALUES
(101,1,50000),(102,2,55000),(103,4,70000);

SELECT E.EMPID,E.FNAME,S.AMOUNT
FROM EMP3 E 
RIGHT JOIN SALARY3 S
ON E.EMPID = S.EMPID;



-- CROSS 
CREATE TABLE STUDENTS(
STD_ID INT PRIMARY KEY,
STD_NAME VARCHAR(50)
);

CREATE TABLE COURSES(
COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(50)
);

INSERT INTO STUDENTS VALUES 
(1,'JOHN'),(2,'AMAN');

INSERT INTO COURSES VALUES
(101,'PYTHON'),(102,'MYSQL');

SELECT S.STD_ID , S.STD_NAME,C.COURSE_NAME
FROM STUDENTS S
CROSS JOIN COURSES C;

-- SELF JOIN
CREATE TABLE EMPSELF(
EMPID INT PRIMARY KEY,
FNAME VARCHAR(50),
MANAGER_ID INT 
);

INSERT INTO EMPSELF VALUES 
(1,'ARUN',3),(2,'MARY',3),(3,'JOHN',NULL);

SELECT * FROM EMPSELF;

SELECT E1.FNAME AS EMPLOYEENAME , E2.FNAME AS MANAGERNAME
FROM EMPSELF E1
LEFT JOIN EMPSELF E2
ON E1.MANAGER_ID  = E2.EMPID;




