SHOW DATABASES;
CREATE DATABASE STRDB;
USE STRDB;

CREATE TABLE EMPLOYEES(
EMPID INT,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
DEPARTMENT VARCHAR(30),
CITY VARCHAR(30)
);

INSERT INTO EMPLOYEES VALUES
(1, 'JOHN', 'SMITH', 'SALES','NEWYORK'),
(2, 'RAVI', 'KUMAR', 'FINANCE', 'LONDON'),
(3,'ROBERT' , 'TAYLOR', 'IT', 'SYDNEY'),
(4, 'EMMA', 'WASTSON', 'HR','TORONTO'),
(5, 'DAVID' , 'CLARK', 'MARKETING', 'PARIS');

SELECT * FROM EMPLOYEES;

-- CONCAT()
SELECT EMPID , CONCAT (FIRSTNAME, ' ' , LASTNAME) AS FULLNAME FROM EMPLOYEES;

-- CONCAT_WS
SELECT EMPID , CONCAT_WS('-',FIRSTNAME,LASTNAME,DEPARTMENT) AS DETAILS FROM EMPLOYEES;

-- LENGTH
SELECT FIRSTNAME , LENGTH(FIRSTNAME) AS NAMELENGTH FROM EMPLOYEES;

SELECT LENGTH('😊');

-- CHAR_LENGTH
SELECT FIRSTNAME , CHAR_LENGTH(FIRSTNAME) AS NAMELENGTH FROM EMPLOYEES;
SELECT CHAR_LENGTH('😊');

-- LOWER() / LCASE()
SELECT LOWER(DEPARTMENT) AS LOWERDEPT,
LCASE(CITY) AS LOWERCITY
FROM EMPLOYEES;

-- UPPER() / UCASE()
SELECT UPPER(DEPARTMENT) AS LOWERDEPT,
UCASE(CITY) AS LOWERCITY
FROM EMPLOYEES;

-- SUBSTRING() / SUBSTR()
SELECT FIRSTNAME, SUBSTRING(FIRSTNAME,1,3) AS SHORTNAME,
SUBSTR(LASTNAME , 2, 4) AS LASTPART FROM EMPLOYEES;

-- INSTR()
SELECT DEPARTMENT , INSTR(DEPARTMENT , 'A') AS POSITIONFA
FROM EMPLOYEES;

SELECT INSTR('HELLO WORLD', 'WORLD') AS POSITIONOFW;

-- LEFT() AND RIGHT()
SELECT FIRSTNAME,
LEFT(FIRSTNAME,2) AS LEFTCHARS,
RIGHT(FIRSTNAME,2) AS RIGHTCHAR
FROM EMPLOYEES;

-- REVERSE()
SELECT FIRSTNAME , REVERSE(FIRSTNAME) AS REVERSED
FROM EMPLOYEES;

-- REPLACE()
SELECT DEPARTMENT , REPLACE(DEPARTMENT, 'A', '@') AS MODIFIED
FROM EMPLOYEES;

-- TRIM
SELECT TRIM('   MYSQL   ') AS TRIMED;
SELECT TRIM(LEADING 'A'  FROM 'AAAAAHELLO') AS LEADTRIMED;
SELECT TRIM(TRAILING 'A'  FROM 'HELLOAAAAA') AS TRALRIMED;


-- -----------------------------------------------------------------------------------------
-- DATE AND TIME FUNCTIONS
-- CURDATE() -- RETURNS CURRENT DATE (YYYY - MM - DDD) FORMAT
SELECT CURDATE() AS TODAYDATE;
SELECT CURRENT_DATE AS TODAYDATE;

-- CURTIME() -- RETURNS CURRENT TIME (HH:MM:SS) FROMAT
SELECT CURTIME() AS CURRENTTIME;
SELECT CURRENT_TIME() AS CURRENTTIME;

-- NOW() -- RETURNS CURRENT DATE AND TIME
SELECT NOW() AS CURRENTDATETIME;

-- SYSDATE() RETURNS SYSTEMS CURRENT DATE AND TIME
SELECT SYSDATE() AS SYSTEMDATE;

-- DATE() -- EXTRACTS DATE PART FROM DATETIME VALE
SELECT DATE('2025-02-07 08:04:30') AS ONLYDATE;

SELECT TIME('2025-02-07 08:04:30') AS ONLYTIME;

-- YEAR() , MONTH() , DAY()
SELECT
YEAR('2025-11-07') AS YEARPART,
MONTH('2025-11-07') AS MONTHPART,
DAY('2025-11-07') AS DAYPART;

-- DAYNAME() -- RETURNS WEEKDAY NAME
SELECT DAYNAME('2026-03-31') AS DAYNAME;

-- MONTHNAME() -- RETURNS MONTH NAME
SELECT MONTHNAME('2026-03-31') AS MONTHNAME;

-- DATE_FROMAT()
-- %Y = YEAR(4DIGITS)
-- %m = MONTH(2 DIGITS)'
-- %M = MONTH NAME
-- % d = DAY
-- %W WEEKDAY NAME
-- %H = HOUR
-- %i = MINUTES
-- %s = SECONDS
SELECT DATE_FORMAT('2026-03-31','%d - %M - %Y') AS FORMATTEDATE;

-- DATEDIF()
SELECT DATEDIFF('2025-12-30' , '2025-12-10') AS DAYDIFFERENCE;

-- ADDDATE() / DATE_ADD()
SELECT ADDDATE('2025-12-20',INTERVAL 10 DAY) AS NEWDATE;

-- SUBDATE() / DATE_SUB()
SELECT SUBDATE('2025-12-30', INTERVAL 10 DAY) AS NEWDATE;

-- ADDTIME() -- ADDS A TIME INTERVAL  TO GIVEN TIME OR DATETIME
SELECT ADDTIME('2025-12-30 03:30:00', '02:15:00') AS ADDEDTIME;

-- SUBTIME() -- ADDS A TIME INTERVAL  TO GIVEN TIME OR DATETIME
SELECT SUBTIME('2025-12-30 03:30:00', '02:15:00') AS ADDEDTIME;

-- TIMEDIFF() -- RETURNS THE DIFFERNCE BETWEEN TWO TIME OR DATETIME VALUES
SELECT TIMEDIFF('10:30:00' , '08:00:00') AS TIMEFIFFERECE;

-- EXTRACT() -- EXTRACTS SPECIFIC PART FROM DATE
SELECT EXTRACT(YEAR FROM '2025-11-07') AS EXTRACTEDYEAR;

 





