CREATE DATABASE SETOPERATIONS;
USE SETOPERATIONS;
CREATE TABLE DEPTA (
EMPID INT PRIMARY KEY,
FNAME VARCHAR(50)
);

CREATE TABLE DEPTB(
EMPID INT PRIMARY KEY,
FNAME VARCHAR(50)
);

INSERT INTO DEPTA VALUES
(1,'JOHN'),(2,'JAMES'),(3,'BOB');

INSERT INTO DEPTB VALUES
(3,'BOB'),(4,'MARK'),(5,'MARY');

SELECT EMPID , FNAME FROM DEPTA
UNION
SELECT EMPID , FNAME FROM DEPTB;

SELECT EMPID , FNAME FROM DEPTA
UNION ALL
SELECT EMPID , FNAME FROM DEPTB;


-- SUBQUERY
CREATE DATABASE SUBQUERY;
USE SUBQUERY;

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY int
);


INSERT INTO EMPLOYEES VALUES
(1,'A','HR',50000),
(2,'B','IT',60000),
(3,'C','FINANCE',55000),
(4,'D','IT',65000),
(5,'E','FINANCE',70000);

-- SCALAR SUBQUERY
-- FINT EMPLOYEES WITH HISHEST SALARY

SELECT EMPNAME , SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

-- MUTIPLE ROW SUBQUERY
-- FIND EMPLLYEES WHO WORK SAME DEPARTMENT AS E 

SELECT EMPNAME , DEPARTMENT 
FROM EMPLOYEES 
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE EMPNAME = 'E');

-- CORRELATED SUBQUERY



-- DERIVED TABLE

-- CALCULATE AVERAGE SALARY BY DEPARTMENT , THEN GET DEPARTMENSTS WITH AVG SALARY > 60000
SELECT DT.DEPARTMENT , DT.AVGSALARY 
FROM(
SELECT DEPARTMENT , AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
) AS DT
WHERE DT.AVGSALARY > 60000;

-- CTE
-- CREATE CTE DEPTAVG TO CALCULATE AVG SALARY PER DEPT

WITH DEPTAVG AS(
SELECT DEPARTMENT , AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
)

SELECT * FROM DEPTAVG 
WHERE AVGSALARY > 60000;

-- VIEWS
CREATE VIEW HIGHSALARYEMLOYEES AS 
SELECT * FROM EMPLOYEES 
WHERE SALARY > 60000;

SELECT * FROM HIGHSALARYEMLOYEES;

INSERT INTO EMPLOYEES VALUES 
(6,'VARUN','MARKETING',80000);

UPDATE EMPLOYEES
SET SALARY = 90000
WHERE EMPNAME = 'A';

--  DROP VEIW VIEWNAME;

