CREATE DATABASE BANKDB1;
USE BANKDB1;

CREATE TABLE ACCOUNTS1(
ACC_ID INT PRIMARY KEY,
ACC_HOLDER VARCHAR(100),
BALANCE DECIMAL(10,2) CHECK (BALANCE>=0)
);

INSERT INTO ACCOUNTS1 VALUES
(1,'A',5000.00),(2,'B',3000.00);

-- AUTOMICITY 
START TRANSACTION;

UPDATE ACCOUNTS1 
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =1;

SELECT * FROM ACCOUNTS1;

UPDATE ACCOUNTS1 
SET BALANCE =BALANCE + 1000
WHERE ACC_ID =2;

COMMIT;

START TRANSACTION;
UPDATE ACCOUNTS1 
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =1;

UPDATE ACCOUNTS1
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =99;

ROLLBACK;
SELECT * FROM ACCOUNTS1;
COMMIT;

-- CONSISTANCY
﻿SELECT * FROM ACCOUNTS1;
START TRANSACTION;

UPDATE ACCOUNTS1
SET BALANCE = BALANCE - 6000
WHERE ACC_ID = 1;

-- ISOLATION
CREATE TABLE ACCOUNTS12(
ACC_ID INT PRIMARY KEY,
ACC_HOLDER VARCHAR(100),
BALANCE DECIMAL(10,2) CHECK (BALANCE>=0)
);
TRUNCATE ACCOUNTS12;
INSERT INTO ACCOUNTS12 VALUES
(1,'FATHER',1000.00);

-- PERSON A 
START TRANSACTION ;
SELECT BALANCE FROM ACCOUNTS12 WHERE ACC_ID = 1;
UPDATE ACCOUNTS12 
SET BALANCE = BALANCE - 800
WHERE ACC_ID = 1;


-- PERSON 
START TRANSACTION ;
SELECT BALANCE FROM ACCOUNTS12
WHERE ACC_ID = 1;

SELECT BALANCE FROM ACCOUNTS12 WHERE ACC_ID = 1;

