CREATE DATABASE LIBRARYDB;
USE LIBRARYDB;

CREATE TABLE BOOKS(
BOOK_ID INT,
TITLE VARCHAR(30),
AUTHOR VARCHAR(30),
GENRE VARCHAR(30),
PUBLICATION_YEAR INT,
PRICE DECIMAL(8,2)
);

INSERT INTO BOOKS VALUES
(1, 'THE GREAT LEADER', 'SCOTT', 'FICTION', 1925, 15.99),
(2, 'TO KILL BIRD', 'HARPER', 'FICTIION' , 1960 , 12.50),
(3, 'THE FUTURE', 'GEROGE', 'DYSTOPIN', 1949, 10.99),
(4,'IKI GAI', 'DONGLEE', 'FICTION', 1951, 14.75);

SELECT * FROM BOOKS;

-- ARTHMETIC OPERATOR

UPDATE BOOKS
SET PRICE = PRICE + 5;
SELECT * FROM BOOKS;

UPDATE BOOKS
SET PRICE  = PRICE - 3
WHERE PUBLICATION_YEAR < 1960;

UPDATE BOOKS
SET PRICE = PRICE * 2
WHERE GENRE = 'FICTION';

UPDATE BOOKS 
SET PRICE = PRICE / 2
WHERE GENRE = 'FICTION';

UPDATE BOOKS
SET PRICE = 9.99
WHERE BOOK_ID % 2 = 0;

SELECT * FROM BOOKS;

-- COMPARISION OPERATOR

SELECT * FROM BOOKS WHERE PUBLICATION_YEAR = 1960;
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR != 1960;
SELECT * FROM BOOKS WHERE PRICE < 15;
SELECT * FROM BOOKS WHERE PRICE > 10;
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR <= 1960;
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR >= 1960;

-- LOGOCAL OPETATOR 
SELECT * FROM BOOKS
WHERE GENRE = 'FICTION' AND PRICE > 15.00;

SELECT * FROM BOOKS
WHERE GENRE = 'DYSTOPIN' OR GENRE = 'COMEDY';

SELECT * FROM BOOKS 
WHERE NOT GENRE = 'FICTION';

-- SPECIAL OPERATOR
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR BETWEEN 1950 AND 1960;
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR NOT BETWEEN 1950 AND 1960;

SELECT * FROM BOOKS WHERE GENRE IN ('FICTION', 'COMEDY'); 
SELECT * FROM BOOKS WHERE GENRE NOT IN ('FICTION', 'COMEDY');

SELECT * FROM BOOKS WHERE PUBLICATION_YEAR IS NULL;
SELECT * FROM BOOKS WHERE PUBLICATION_YEAR IS NOT NULL;








