SHOW DATABASES;
USE COMPANYDB;
SHOW TABLES;
DESC EMP;

SELECT * FROM EMP;

-- GRANT
-- GRANT UPDATE , DELETE ON COMPANYDB.* TO 'username' @ 'localhost';
-- GRANT UPDATE , DELETE ON COMPANYDB.EMP TO 'username'  @ 'localhost';

-- REVOKE PERMISSIONS
-- REVOKE UPDATE , DELETE ON COMPANYDB.* FROM 'username'  @ 'localhost'
-- REVOKE UPDATE , DELETE ON COMPANYDB.EMP FROM 'username'  @ 'localhost'

-- ROLLBACK
START TRANSACTION;
SELECT * FROM EMP;
UPDATE EMP
SET AGE  = 40
WHERE EMP_ID  = 'E001';

SELECT * FROM EMP;
ROLLBACK;

COMMIT;

-- SAVEPOINT

SELECT * FROM EMP;

START TRANSACTION;
UPDATE EMP
SET AGE  = 40
WHERE EMP_ID  = 'E001';
SELECT * FROM EMP;
SAVEPOINT MY_SAVEPOINT;

ROLLBACK TO SAVEPOINT MY_SAVEPOINT;
ROLLBACK;
SELECT * FROM EMP;

COMMIT;

-- SELECT
SELECT * FROM EMP;
SELECT FIRSTNAME,AGE,DEPT FROM EMP;
SELECT * FROM EMP
WHERE DEPT = 'IT';

SELECT * FROM EMP
WHERE AGE > 30;

SELECT * FROM EMP
WHERE AGE = 30 AND DEPT = 'IT';






 